name: Publish

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Publish the extension to VS Code Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Publish
        run: make compile_and_package && make publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
